#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run wuth sudo" 
   exit 1
fi

update-alternatives --set default.plymouth /usr/share/plymouth/themes/dbaa-vert-splash/dbaa-vert-splash.plymouth

ln -sf /etc/default/grub_vert /etc/default/grub

update-grub

