#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run wuth sudo"
   exit 1
fi

cd /etc/default

cp ./grub_horiz /etc/default/grub_horiz
cp ./grub_vert /etc/default/grub_vert

ln -s /etc/default/grub_horiz /etc/default/grub

update-grub
