#!/bin/bash 

cd ~/SCO

nohup './SCO-Linux-x8664/SCO-Linux-x86+64.x86_64' -screen-fullscreen 1 &

xdotool key Tab
xdotool key Tab
xdotool key Tab
xdotool key Tab
xdotool key Tab

xdotool key Return

unclutter -idle 0.01 -root


