#!/bin/bash 

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run wuth sudo" 
   exit 1
fi

cd /etc/default

cp /etc/default/grub /etc/default/grub_horiz
mv /etc/default/grub /etc/default/grub_vert

ln -s /etc/default/grub_horiz /etc/default/grub

echo "You need to edit /etc/default/grub_vert"
echo "replace and set GRUB_CMDLINE_LINUX=\"video=efifb fbcon=rotate:1\""

update-grub
