#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run wuth sudo" 
   exit 1
fi

 cd ../
 
 cp -r ./dbaa-splash /usr/share/plymouth/themes
 rm /usr/share/plymouth/themes/dbaa-splash/install-dbaa-splash
 
 update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/dbaa-splash/dbaa-splash.plymouth 100
 
 update-alternatives --set default.plymouth /usr/share/plymouth/themes/dbaa-splash/dbaa-splash.plymouth
 
 update-initramfs -u 
 
 update-grub2

 echo "You can remove the folder this script is in."